import { Action } from './types/action';

export const mockActions: Action[] = [
  {
    id: 1,
    actionPlan: "Smart Instruments State (Updated)",
    tags: "",
    area: "Storage and handling",
    discipline: "Automation",
    assignedTo: "FAHMI/KHALID",
    fromDate: "2025-02-04",
    toDate: "2025-02-06",
    duration: 2,
    status: "Done"
  },
  {
    id: 2,
    actionPlan: "Smart Instruments State (Updated)",
    tags: "",
    area: "Washing",
    discipline: "Automation",
    assignedTo: "FAHMI/ALAOUI",
    fromDate: "2025-02-04",
    toDate: "2025-02-06",
    duration: 2,
    status: "Done"
  },
  {
    id: 3,
    actionPlan: "Smart Instruments State (Updated)",
    tags: "",
    area: "Flotation",
    discipline: "Automation",
    assignedTo: "FAHMI/EL MIHI",
    fromDate: "2025-02-04",
    toDate: "2025-02-06",
    duration: 2,
    status: "Done"
  },
  {
    id: 4,
    actionPlan: "Correction fixation des caillbotis",
    tags: "",
    area: "Tailing Management",
    discipline: "Mechanical",
    assignedTo: "Naoufal/Nejjari",
    fromDate: "2025-02-04",
    toDate: "2025-02-07",
    duration: 3,
    status: "Done"
  },
  {
    id: 5,
    actionPlan: "Flexible S 150 pour les pompes Drageuses",
    tags: "",
    area: "Washing",
    discipline: "Mechanical",
    assignedTo: "SAMIH",
    fromDate: "2025-02-07",
    toDate: "2025-02-09",
    duration: 2,
    status: "Done"
  },
  {
    id: 6,
    actionPlan: "Vérification des PDR +Solution possibles vannes",
    tags: "",
    area: "Washing",
    discipline: "Mechanical",
    assignedTo: "MACALOU/Zahir",
    fromDate: "2025-02-09",
    toDate: "2025-02-11",
    duration: 2,
    status: "Delay"
  },
  {
    id: 7,
    actionPlan: "Définition flux des PTWs (JESA AM/OCP)",
    tags: "",
    area: "Storage and handling",
    discipline: "Automation",
    assignedTo: "",
    fromDate: "2025-02-11",
    toDate: "2025-02-12",
    duration: 1,
    status: "Delay"
  },
  {
    id: 8,
    actionPlan: "Remote access for FLS by HNW for SQH + Flottation",
    tags: "",
    area: "Flotation",
    discipline: "Digitization",
    assignedTo: "Fahmi / Mouhat",
    fromDate: "2025-02-11",
    toDate: "2025-02-13",
    duration: 2,
    status: "Done"
  },
  {
    id: 9,
    actionPlan: "Changement d'alimentation du crible de raw water à process water",
    tags: "",
    area: "Washing",
    discipline: "Mechanical",
    assignedTo: "DROUICHE",
    fromDate: "2025-02-11",
    toDate: "2025-02-14",
    duration: 3,
    status: "Done"
  },
  {
    id: 10,
    actionPlan: "Résoudre le problème de VFD de la pompe 230A-SP-02D",
    tags: "230A-SP-02D",
    area: "Washing",
    discipline: "Electrical",
    assignedTo: "Ajmahri/Lamtabti/Weir",
    fromDate: "2025-04-21",
    toDate: "2025-04-23",
    duration: 2,
    status: "Done"
  },
  {
    id: 11,
    actionPlan: "Résolution problème emplacement des ppe sup",
    tags: "",
    area: "Storage and handling",
    discipline: "Automation",
    assignedTo: "",
    fromDate: "2025-02-11",
    toDate: "2025-02-18",
    duration: 7,
    status: "Done"
  },
  {
    id: 12,
    actionPlan: "Les autorisations de Honeywell",
    tags: "",
    area: "Storage and handling",
    discipline: "Automation",
    assignedTo: "Zahir",
    fromDate: "2025-02-14",
    toDate: "2025-02-16",
    duration: 2,
    status: "Done"
  },
  {
    id: 13,
    actionPlan: "Replacement of the faulty Electrovalve XV8415 with a new one",
    tags: "310A-XV-8415",
    area: "Flotation",
    discipline: "Automation",
    assignedTo: "EL MIHI/Oxycoupe",
    fromDate: "2025-01-15",
    toDate: "2025-01-16",
    duration: 1,
    status: "Done"
  },
  {
    id: 14,
    actionPlan: "Changement de la vanne 4313",
    tags: "",
    area: "Storage and handling",
    discipline: "Automation",
    assignedTo: "Zahir",
    fromDate: "2025-02-15",
    toDate: "2025-02-17",
    duration: 2,
    status: "Done"
  },
  {
    id: 15,
    actionPlan: "List all bypassed interlocks for scrubbing & screening",
    tags: "SKAKO",
    area: "Washing",
    discipline: "Automation",
    assignedTo: "ALAOUI",
    fromDate: "2025-02-16",
    toDate: "2025-02-16",
    duration: 0,
    status: "Done"
  },
  {
    id: 16,
    actionPlan: "Check the vibration of pump 320A-SP-01D",
    tags: "",
    area: "Flotation",
    discipline: "Mechanical",
    assignedTo: "NEJJARI",
    fromDate: "2025-02-17",
    toDate: "2025-02-19",
    duration: 2,
    status: "Delay"
  },
  {
    id: 17,
    actionPlan: "CB1 Belt Scale GSD file issue and Lack of totalizer output and calibration",
    tags: "CB1 Belt Scale",
    area: "Storage and handling",
    discipline: "Automation",
    assignedTo: "Khalil/Dominik/KHALID",
    fromDate: "2025-03-03",
    toDate: "2025-03-14",
    duration: 11,
    status: "In Progress"
  },
  {
    id: 18,
    actionPlan: "Bedmass sensor endommagé au cone du Underflow du décanteur.",
    tags: "410APIT0403",
    area: "Tailing Management",
    discipline: "Process",
    assignedTo: "",
    fromDate: "2025-03-25",
    toDate: "2025-03-28",
    duration: 3,
    status: "Not started"
  },
  {
    id: 19,
    actionPlan: "Installer des abris pour les pompes et les coffrets électriques",
    tags: "",
    area: "Washing",
    discipline: "Mechanical",
    assignedTo: "MACALOU/WEIR",
    fromDate: "2025-03-28",
    toDate: "2025-04-01",
    duration: 4,
    status: "Not started"
  },
  {
    id: 20,
    actionPlan: "Integration of machines storage & Handling in DCS",
    tags: "ST110/ST130/RP120/RP140",
    area: "Storage and handling",
    discipline: "Digitization",
    assignedTo: "MOUHAT/FLS/HW",
    fromDate: "2025-04-01",
    toDate: "2025-04-10",
    duration: 9,
    status: "Not started"
  }
];